name: bbo_music_player
description: "Beats By One"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # 국제화
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # 기타 의존성
  cupertino_icons: ^1.0.8
  google_mobile_ads: ^6.0.0
  file_picker: ^8.0.0
  ffmpeg_kit_flutter_new_min: ^3.0.0
  dart_tags: ^0.4.1
  file_selector: ^1.0.0
  path: ^1.9.0
  file_saver: ^0.3.1
  flutter_overlay_window: ^0.5.0
  webview_flutter: ^4.7.0
  permission_handler: ^12.0.1
  rename: ^3.1.0
  shared_preferences: ^2.3.2
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # l10n 코드 생성 활성화 (필수)
  generate: true

  assets:
    - assets/buttonImage/
    - assets/
    - LICENSES/THIRD-PARTY-NOTICES.txt
    - open-source/ffmpeg/LICENSES/ffmpeg-kit-LICENSE
    - open-source/ffmpeg/LICENSES/COPYING.LGPLv2.1
    - open-source/ffmpeg/LICENSES/COPYING.LGPLv3
    - open-source/ffmpeg/ffmpeg-config.txt
    - open-source/ffmpeg/WHERE-TO-GET-SOURCE.txt